### ISSUE TITLE
Community - pridani zaznamu

### ISSUE THREAD

**Issue by milkydan** [oarepo/oarepo-communities#30]
Zalozil jsem communitu "darkmylan", ve VO_du_test jsem si udelal dve skupiny pro publishery a curatory a prihodil na ne prislusne resourcy. V oarepo cli jsem na ty skupiny pak navesil prislusne role. Nejde mi ale vyrobit zaznam s tim ze dostavam chybu ze nemam permissions.

**Comment by milkydan** [comment]
`message: "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."
status: 403`

**Comment by mirekys** [comment]
Bylo tim, ze kuratori v komunite nemeli pravo na create, to meli jen memberi a skupina kuratoru nebyla zaroven cleny komunity
